```
=================================================
Final Project

Nama  : Grup 1 (Kenny, Mark, Christian)
Batch : CODA-015-RMT

Program ini dibuat untuk melakukan automatisasi transform dan load data dari Kaggle ke NeonDB dengan harapan data yang sudah ada di database dapat digunakan data analyst dalam melakukan proses analysis.
=================================================
```

URL PPT = https://canva.link/j8yxkzoeacqtos8

URL Dashboard = https://lookerstudio.google.com/reporting/b0f5a213-35d2-4e15-94e9-928cc8f5dfb9

In [1]:
import pandas as pd
from sqlalchemy import create_engine

# Connection string
engine = create_engine(
    "postgresql+psycopg2://neondb_owner:npg_n2udKjfDxPU6@ep-flat-dew-a18kk5pg-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require"
)

# Load table into pandas DataFrame
dim_customer = pd.read_sql("SELECT * FROM dim_customer", engine)
dim_payment = pd.read_sql("SELECT * FROM dim_payment", engine)
dim_service = pd.read_sql("SELECT * FROM dim_service", engine)
fact_subscription = pd.read_sql("SELECT * FROM fact_subscription", engine)
# Show data
fact_subscription.head()

,id,CustomerID,Service_id,Payment_id,Tenure,MonthlyCharges,TotalCharges,Churn
0,0,7590-VHVEG,0,0,1,29.85,29.85,No
1,1,5575-GNVDE,1,1,34,56.95,1889.50,No
2,2,3668-QPYBK,2,2,2,53.85,108.15,Yes
3,3,7795-CFOCW,3,3,45,42.30,1840.75,No
4,4,9237-HQITU,4,4,2,70.70,151.65,Yes

In [2]:
fact_subscription.to_csv('fact_subscription.csv')

In [3]:
dim_customer.head()

   CustomerID  Gender Partner  SeniorCitizen Dependents
0  7590-VHVEG  Female     Yes              0         No
1  5575-GNVDE    Male      No              0         No
2  3668-QPYBK    Male      No              0         No
3  7795-CFOCW    Male      No              0         No
4  9237-HQITU  Female      No              0         No

In [4]:
dim_customer.to_csv('dim_customer.csv')

In [5]:
dim_payment.head()

   Payment_id        Contract PaperlessBilling     PaymentMethod is_automatic
0           0  Month-to-month              Yes  Electronic check           no
1           1        One year               No      Mailed check           no
2           2  Month-to-month              Yes      Mailed check           no
3           3        One year               No     Bank transfer          yes
4           4  Month-to-month              Yes  Electronic check           no

In [6]:
dim_payment.to_csv('dim_payment.csv')

In [7]:
dim_service.head()

,Service_id,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,0,No,No phone service,DSL,No,Yes,No,No,No,No
1,1,Yes,No,DSL,Yes,No,Yes,No,No,No
2,2,Yes,No,DSL,Yes,Yes,No,No,No,No
3,3,No,No phone service,DSL,Yes,No,Yes,Yes,No,No
4,4,Yes,No,Fiber optic,No,No,No,No,No,No

In [8]:
dim_service.to_csv('dim_service.csv')

### Great Expectation

In [9]:
# Create a data context

from great_expectations.data_context import FileDataContext

context = FileDataContext.create(project_root_dir='./')

In [11]:
# Give a name to a Datasource. This name must be unique between Datasources.
datasource_name = 'fact_subscription_2'
datasource = context.sources.add_pandas(datasource_name)

# Give a name to a data asset
asset_name = 'fact_subscription_asset'
path_to_data = 'fact_subscription.csv'
asset = datasource.add_csv_asset(asset_name, filepath_or_buffer=path_to_data)

# Build batch request
batch_request = asset.build_batch_request()

In [12]:
# Creat an expectation suite
expectation_suite_name = 'suite1' #menamakan suite
context.add_or_update_expectation_suite(expectation_suite_name) #membuat suite

# Create a validator using above expectation suite
validator = context.get_validator(
    batch_request = batch_request,
    expectation_suite_name = expectation_suite_name
)

# Check the validator
validator.head()

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

,Unnamed: 0,id,CustomerID,Service_id,Payment_id,Tenure,MonthlyCharges,TotalCharges,Churn
0,0,0,7590-VHVEG,0,0,1,29.85,29.85,No
1,1,1,5575-GNVDE,1,1,34,56.95,1889.50,No
2,2,2,3668-QPYBK,2,2,2,53.85,108.15,Yes
3,3,3,7795-CFOCW,3,3,45,42.30,1840.75,No
4,4,4,9237-HQITU,4,4,2,70.70,151.65,Yes

### Expectation 1

In [13]:
validator.expect_column_values_to_be_unique(column="CustomerID")

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 7043,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

### Expectation 2

In [14]:
validator.expect_column_values_to_be_between(
    column="Tenure",
    min_value=0,
    max_value=972
)

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 7043,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

### Expectation 3

In [15]:
validator.expect_column_to_exist(
    column="Churn"
)

Calculating Metrics:   0%|          | 0/2 [00:00<?, ?it/s]

{
  "success": true,
  "result": {},
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

### Expectation 4

In [16]:
validator.expect_column_values_to_be_in_type_list(
    column="TotalCharges",
    type_list=["float64"]
)

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "observed_value": "float64"
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

### Expectation 5

In [17]:
validator.expect_column_values_to_not_be_null(
    column="MonthlyCharges"
)

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 7043,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": []
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

### Expectation 6

In [18]:
validator.expect_column_values_to_be_in_set(
    column="TotalCharges",
    value_set=[0],
    row_condition="Tenure == 0",
    condition_parser="pandas"
)

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 11,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

### Expectation 7

In [20]:
# Give a name to a Datasource. This name must be unique between Datasources.
datasource_name = 'dim_service_2'
datasource = context.sources.add_pandas(datasource_name)

# Give a name to a data asset
asset_name = 'dim_service_asset'
path_to_data = 'dim_service.csv'
asset = datasource.add_csv_asset(asset_name, filepath_or_buffer=path_to_data)

# Build batch request
batch_request = asset.build_batch_request()

# Creat an expectation suite
expectation_suite_name = 'suite2' #menamakan suite
context.add_or_update_expectation_suite(expectation_suite_name) #membuat suite

# Create a validator using above expectation suite
validator = context.get_validator(
    batch_request = batch_request,
    expectation_suite_name = expectation_suite_name
)

# Check the validator
validator.head()

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

,Unnamed: 0,Service_id,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,0,0,No,No phone service,DSL,No,Yes,No,No,No,No
1,1,1,Yes,No,DSL,Yes,No,Yes,No,No,No
2,2,2,Yes,No,DSL,Yes,Yes,No,No,No,No
3,3,3,No,No phone service,DSL,Yes,No,Yes,Yes,No,No
4,4,4,Yes,No,Fiber optic,No,No,No,No,No,No

In [21]:
validator.expect_column_values_to_be_in_set(
    column="InternetService",
    value_set=["Fiber optic", "DSL", "No"],
    mostly=1.0  # Semua baris harus sesuai
)

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

{
  "success": true,
  "result": {
    "element_count": 7043,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}